### ISSUE TITLE
MBeanFieldGroup: standard Vaadin validation stops process if an invalid value is found

### ISSUE THREAD

**Issue by sebdavid** [viritin/viritin#113]
Hi,

I'm using the ```MBeanFieldGroup``` to manage fields validation and the FieldGroupListener. I'm facing a behavior that is unwanted in my mind, concerning the ```isValid()``` method.

This method can be 'cut' in 3 parts :
1. standard Vaadin validation
2. validation through MValidators
3. jsr-303 validation

The problem is that for the first part, the whole validation process is stopped if one Vaadin validation fails, due to :
- the use of the Vaadin basic FieldGroup.isValid, which stop processing fields when an invalid value is found
- the if statement ```if (propertiesValid) {...```, preventing the rest of the code to be executed

From a user point of view, it can lead to the following situation :
1. a form is displayed with fields A, B and C. The field A is set as required via ```setRequired(true)```
2. the user modifies fields A, B, C
3. one modification leads to an invalid value caught by an MValidator for the field C : it is displayed in error
4. the user clear the field A
5. field A is displayed in error (because it's required), but the error on field C is removed !!

So the problem is that the error on field C is removed, whereas the error still exists.

Is there a reason for that ?

Maybe removing the ```if (propertiesValid) {...```, and including the ```propertiesValid``` var in the return statement would be sufficient ?
```java
return jsr303ValidateBean(getItemDataSource().getBean()) && propertiesValid && ok;
```

Thanks in advance for your answer.

**Comment by mstahv** [comment]
Hi, this is how the Vaadin validators are (for some reason) designed to work. I agree with you that all of them should be examined. If you have a good example use case, please attach it here (with all validators you are using). I could look into if MBeanFieldGroup could in the future bypass the built-in Vaadin validation logic altogether and "fix" this. Basic Vaadin validators could be run with the same logic that is used for MValidator's currently.

Or then you could just use MValidator's for all programmatic validation?

**Comment by sebdavid** [comment]
Hi,

Actually, I'm just using the native "setRequired" method from Vaadin validator, nothing else. But I have two MValidators to perform cross-fields validations, for some business rules. My problem is essentially due to the ```if (propertiesValid) {...``` which blocks the MValidators and jsr303 validation (even if I'm not using this last one) if one of my required field is not filled (propertiesValid became false), possibly leading to the situation described in my previous post.

I could bypass the Vaadin "required" validation by not using the ```setRequired(true)``` method, and adding some MValidator to check the required field, but I think I will loose the required indicator native management (the little red star), or I would have to manually manage it.

**Comment by mstahv** [comment]
Ah, indeed. I guess the solution would still be the same. Vaadin handles setRequired(true) as a kind of a special built in validator.

I you have time to extract an example, it would be valuable in finding the perfect solution.

**Comment by sischi** [comment]
Hi,

because I am facing this exact "issue", I have extracted an example that should clearify the situation. The example is a form to register a new user.
The entity User has two property validations: One for the length of the username and one for the email format:
`@Size(min=3, max=10)
private String username = "";
@Email
@NotBlank
private String email = "";`
The MyForm class builds the form and adds three validators for cross-field-validation:
- username: check if the username alreadey exists (in this example, the only user that exists is "test")
- newPassword1: check if the "password"-labeled field is not empty
- newPassword2: if the "password"-labeled field is not empty, then check if it matches with the repitition

If I now fill in the form like
![curr_situation1](https://cloud.githubusercontent.com/assets/2520013/18340029/111b7ba2-75a3-11e6-803e-d7d41c9c39b0.png)
where the email is missing, the username "test" and the wrong password-repitition are not validated since I insert an email in correct format like 
![curr_situation2](https://cloud.githubusercontent.com/assets/2520013/18340055/2ff1024a-75a3-11e6-8b03-826b6b0b0cb6.png)
But i want the user to see, that the username is already used and the passwords doesn't match, even if he not yet filled up all the property-validation fields like
![desired_behaviour](https://cloud.githubusercontent.com/assets/2520013/18340068/3f858550-75a3-11e6-920f-0910996aa82c.png)

The latter I could achieve by changing the isValid() method of class MBeanFieldGroup from
`@Override
public boolean isValid() {
	// ...
	if (propertiesValid) {
		boolean ok = true;
		for (MValidator<T> v : mValidators.keySet()) {
			// ... bean level validation ...
		}
		return jsr303ValidateBean(getItemDataSource().getBean()) && ok;
	}
	return false;
}`
to something like
`@Override
public boolean isValid() {
	// ...
	boolean ok = false;
	if (propertiesValid) {
		ok = true;
	}
	for (MValidator<T> v : mValidators.keySet()) {
		// ... bean level validation ...
	}
	return jsr303ValidateBean(getItemDataSource().getBean()) && ok;
}`

Do you see any downsides regarding my modification? Will I loose any built-in features with that implementation?

Here is the related code: [validation_example.txt](https://github.com/viritin/viritin/files/461029/validation_example.txt)

I hope this example is what you were asking for.

**Comment by mstahv** [comment]
I changed the validation in https://github.com/viritin/viritin/commit/0e931a8c04e0de04d4d49da5d51612739420f872 so that all property validators are executed and als so that bean level validators are executed, even though property validators don't pass. This may break some existing apps so I added a mode that can revert to the old style, but I think this is better for most apps.

**Comment by wassimz** [comment]
Hi,
With the new default validation model. my app doesn't work anymore as per default field are empty. How can activate the proposed mode to use the old model ??

**Comment by apolds** [comment]
Try setValidateAllProperties(false) on the beanFielGroup of your abstractForm.
