### ISSUE TITLE
MGrid.withGeneratedColumn - new generated Column is not listed in grid

### ISSUE THREAD

**Issue by apolds** [viritin/viritin#219]
If I add a generated column with a non existent property name to a typed MGrid, it will not be shown.

Example:
I want to show a list of users. The class User includes the properties "username", "firstname" and "lastname". The following code only shows those three columns. The generated column "fullname" is missing.
```
MGrid testGrid = new MGrid<User>(User.class)
	.lazyLoadFrom(
		(firstRow) -> userRepository.findAllBy(new PageRequest(firstRow / 100, 100)),
		() -> (int) userRepository.count(),
		100
	)
	.withGeneratedColumn("fullname", p -> p.getFirstname() + " " + p.getLastname());
```

If I change the property name of the generated column to an existent property name, the generated content will be shown instead of the value of the original property.
In the following example the grid shows the three columns "username", firstname" and "lastname". the content of the column "username" shows the generated content (firstname + " " + lastname).
```
MGrid testGrid = new MGrid<User>(User.class)
	.lazyLoadFrom(
		(firstRow) -> userRepository.findAllBy(new PageRequest(firstRow / 100, 100)),
		() -> (int) userRepository.count(),
		100
	)
	.withGeneratedColumn("username", p -> p.getFirstname() + " " + p.getLastname());
```

Isn't it possible to add generated columns with new property names?

**Comment by sischi** [comment]
Hi,

I tried to analyze this issue with the following result:

IMO the issue lies in the class GeneratedPropertyListContainer. It should override the method getContainerPropertyIds() of the extended ListContainer to add the keySet (the propertyIds) of the propertyGenerator-map.

By default, the typed MGrid<T> creates an empty typed ListContainer<T> (if none is set in the constructor) which adds all the properties of the Class T to the columns list of the extended Grid class.
If you now call the withGeneratedColumn method of that just created MGrid, it casts the ListContainer to GeneratedPropertyListContainer (which extends ListContainer) and adds the new propertyID along with the provided ValueGenerator to the property-generator-map (propertyGenerators) of the GeneratedPropertyListContainer.
At this point, all looks good, but if you try to call addColumn on the MGrid, you will get the "Property ID '...' does not exists in the container" message. The reason for this is, that GeneratedPropertyListContainer does not override the getContainerPropertyIds() so that a call of this method is delegated to the underlying ListContainer which only knows about the propertyIds of the given type T.

So a simple implementation of the overriding method getContainerPropertyIds() in GeneratedPropertyListContainer that would solve this issue could look like this:

``` Java
	@Override
    public Collection<String> getContainerPropertyIds() {
        // create returned list of propertyIds
        ArrayList<String> properties = new ArrayList<String>();
    	
    	// add all propertyIds of the underlying ListContainer
    	properties.addAll(super.getContainerPropertyIds());

    	// add the propertyIds for all the given generators
        properties.addAll(propertyGenerators.keySet());
        
        return properties;
    }
```

As a workaround you can add the propertyId to the underlying ListContainer manually, after calling the withGeneratedColumn, like:

``` Java
// add value generator with propertyId 'foo'
mgrid.withGeneratedColumn("foo", u -> u.getLastname() +", "+ u.getFirstname());
// add the new propertyId to the underlying ListContainers properties-list
((Collection<String>) mgrid.getContainerDataSource().getContainerPropertyIds()).add("foo");
// add the new column to the MGrid
mgrid.addColumn("foo");
```

**Comment by mstahv** [comment]
Uhh, those generatedproperty things, not my favourites. I'll give this a try...

**Comment by mstahv** [comment]
The column seems to be made visible if you also define it using "withProperties(String...)" method, but should be definitely visible without separate definition.
