### ISSUE TITLE
viritin 1.59 can throw a NPE on sort

### ISSUE THREAD

**Issue by PhineasClick** [viritin/viritin#257]
The following exception is thrown :

java.lang.NullPointerException
	at org.vaadin.viritin.ListContainer.getContainerProperty(ListContainer.java:240)
	at org.vaadin.viritin.ListContainer$PropertyComparator.compare(ListContainer.java:520)
	at java.util.TimSort.countRunAndMakeAscending(Unknown Source)
	at java.util.TimSort.sort(Unknown Source)
	at java.util.Arrays.sort(Unknown Source)
	at java.util.ArrayList.sort(Unknown Source)
	at java.util.Collections.sort(Unknown Source)
	at org.vaadin.viritin.ListContainer.sort(ListContainer.java:421)
	at org.vaadin.viritin.FilterableListContainer.sort(FilterableListContainer.java:183)
	at com.vaadin.data.util.GeneratedPropertyContainer.sort(GeneratedPropertyContainer.java:542)
	at com.vaadin.ui.Grid.sort(Grid.java:6103)
	at com.vaadin.ui.Grid.setSortOrder(Grid.java:6058)
	at com.vaadin.ui.Grid.setSortOrder(Grid.java:6030)

This don't happen with viritin 1.58

**Comment by mstahv** [comment]
Hi,

Could you post an example that can be used to reproduce the issue?

cheers,
matti

**Comment by PhineasClick** [comment]
I will try to assemble zum Code to reproduce it and post it as soon as possible.

But meanwhile, when you look at the Line in Error :

@Override
    public Property getContainerProperty(Object itemId, Object propertyId) {
        return getItem(itemId).getItemProperty(propertyId);
}

getItem can return null, wich will lead to an uncaught NPE for getItemProperty.

**Comment by connor-bracewell** [comment]
I was about to post this issue and provide a potential solution - I can confirm I encountered this issue on my project today. Unfortunately I don't have time to produce a minimal test case but I did write up a quick solution to use in my project.

The issue is that `getContainerProperty()` uses the overridden `getItem()` from `FilterableListContainer` that returns `null` if the item has been filtered from the list. When the list gets sorted, `getContainerProperty()` gets called for the comparator, and the null gets dereferenced.

See https://github.com/connor-bracewell/viritin/commit/cb873f2059b96300f77eb2b2934a70510e947bd3 for the quick-fix I put together for my project. If anyone has any feedback I'd be happy to hear it.

I noticed the test suite seems to have a test for this, but its not capturing it for some reason. Someone with more time should probably take a look at the test case and figure out the issue.

**Comment by mstahv** [comment]
It looks like BeanContainer in the core is doing exactly the same, but contains a comment if this should really be done. Also it contains an additional null check.

I don't really see why that property of a filtered out item should ever be requested by the component, that is why I'd love to see what really happens. Also it would be great to have a test case for this to make sure the fix really helps. I'll try to put out a release with fix soon, but I would really appreciate if somebody could come up with a reduced test case.

**Comment by connor-bracewell** [comment]
Okay, I've done some testing and the implementation is wrong (and will throw NPEs) for any valid input that has at least one entry filtered out by some filter.

The current test cases aren't catching it because they aren't set up properly - add `p.setId(i);` at line 54 in `FilterableListContainerTest.java` to properly set the ids (so `Person.equals()` behaves properly), and the test will fail with the same error (right now all the Person items are `equal` so `filteredItems.contains()` always returns `true` if `filteredItems` contains any elements, so `FilteredListContainer.getItem()` never returns `null`).

Looks like this was broken with the comparator change in https://github.com/viritin/viritin/commit/bcec4d076feaf5abc0ab471164bd972afaec79b5#diff-160c3861c99fba4fafff234589fb1c4a.

At the very least the test suite should be updated to catch it properly. The comparator implementation could be reverted, or a different fix could be implemented (à la my quick fix from yesterday).

Let me know your thoughts.

**Comment by connor-bracewell** [comment]
Actually, per the Vaadin Javadoc, getContainerProperty should return `null` if the container doesn't contain the given item(https://vaadin.com/api/com/vaadin/data/Container.html#getContainerProperty-java.lang.Object-java.lang.Object-). I think the best solution (to solve this and bring `ListContainer` into spec) is just to add the null check in and have the Comparator check that the returned Property is not null.

I've prepared a fix: https://github.com/viritin/viritin/compare/master...connor-bracewell:master

If this seems like the right approach let me know and I'll submit a pull request.

**Comment by mstahv** [comment]
The null check looks like a right change to me. Wouldn't it be enough though to have it only in getContainerProperty method though?

**Comment by mstahv** [comment]
Opened the project and not enough indeed.

**Comment by mstahv** [comment]
Looks like I was able to do the pull request as well from your branch. Let me know if it is not ok :-)
