### ISSUE TITLE
ClearableTextField problem

### ISSUE THREAD

**Issue by blueiceprj** [viritin/viritin#258]
Hi, 
I used ClearableTextField and set required=true. But may be textfield has a appearance problem. (asterisk)
<img width="904" alt="screen shot 2016-11-23 at 03 17 49" src="https://cloud.githubusercontent.com/assets/1829975/20542470/ed59b7e6-b12b-11e6-9aca-418381709efd.png">

**Comment by vonloxley** [comment]
Thank you for reporting this. I’ll fix it in a couple of days.

**Comment by mstahv** [comment]
Should probably proxy some required styles to the textfield. @vonloxley, let me know if you need help with this.

**Comment by vonloxley** [comment]
Hi @mstahv!

I really could need some help here. Last evening I spend an hour trying to figure out out to fix the form rendering, but all paths I went down (switching to CustomField, writing a ComponentExtension) would require a lot of coding which I feel is too much this very simple component.

I don’t have any experience with vaadin styling or the used css, so I would gladly accept some help.

Your time would probably be well spend, since [other people](https://vaadin.com/forum/#!/thread/8772107/8860402) seem to have similar problems.

Thanks a lot

Niki

**Comment by mstahv** [comment]
I made a largish refactoring in [d4ab351] so that the field now extends form CustomField. Could you test that in your own app? There is probably lot of things missing. If you can look at it soon we could maybe get the change to 1.60 which I plan to build soon. Otherwise I'll postpone this to 1.61.

**Comment by blueiceprj** [comment]
Hi Mati,

Thanks for your helps. I tried your solution. But the problem at textfield. When I called the field or beanfieldgroup validation(isValid or validate) methods that required validation error not appeared.
Look at screen shot my attachment that clearablefield's css cannot changed but other required fields's css changed and covered red lines.

Thanks.

<img width="901" alt="screen shot 2016-11-25 at 23 32 41" src="https://cloud.githubusercontent.com/assets/1829975/20632564/9dd374e8-b368-11e6-8ac7-253486fc7770.png">

**Comment by vonloxley** [comment]
Hi Matti!

The result looks good to me. Thanks a lot!

**Comment by mstahv** [comment]
I'll still need to check out the databinding stuff, I guess I need to do some magic in setPropertyDataSource still.

**Comment by mstahv** [comment]
The size should now (since https://github.com/viritin/viritin/commit/2c5b229f97aee408811614d9238aea562b74cdaa)  work ok with ClearableTextField, but styling is still somewhat "suboptimal", although improved with errors. Currently error style is propagated to textfield, but at least I'd like the button to be bit "red" as well. Same for focus indication, it should probably go around the whole field, but getting that work perfectly might need some client side haxing.

**Comment by blueiceprj** [comment]
Hi Matti;

Thanks for great job. It is ok for me.

Best regards
