### ISSUE TITLE
Add V8 EnumSelect support

### ISSUE THREAD

**Issue by StarGuardian** [viritin/viritin#310]
Now there is no EnumSelect as V8 widget.

I'm going to make PR soon.

**Comment by StarGuardian** [comment]
Created PR #310 Please check it.

**Comment by mstahv** [comment]
Looks pretty good to me. I guess we don't now have any way in V8 to discover the enum type automatically, so that makes this bit less useful than before, but one can still avoid one function call. 

Would you still add a usage example or test to the test directory?

**Comment by StarGuardian** [comment]
OK, I will do it next week

**Comment by mstahv** [comment]
I pulled the change in, but it would be cool the get the test/example cases in as well!

**Comment by StarGuardian** [comment]
Sorry for delay. I checked latest version of viritin and found out that you supported ElementCollectionField, so AddressType field used EnumSelect now (example EditPersonV8). Is that enought? Or should I add another test/example?

**Comment by mstahv** [comment]
Yeah, I used that there, maybe that is enough, unless you want to create something that covers more use cases.

BTW. I changed the simpler constructor to use null as caption instead of "". For some reason Vaadin (8?) seems to interpret that empty caption should be rendered and causes weird looking rendering for the EditPersonV8 test. It would be great if you can try out a local build in your app to see that everything works as it should.
