### ISSUE TITLE
Issue using the MFormlayout

### ISSUE THREAD

**Issue by wassimz** [viritin/viritin#51]
Hi,

I am using the MFormlayout component as described in many examples (using the viritin addon) coupled with the CDI addon. The problem is every time I am accessing a view injecting the form layout, I have the following warning for all included component:

[com.vaadin.ui.ConnectorTracker] (http-/127.0.0.1:8080-6) An already registered connector was registered again:

Sure the application work fine within this warning but just to know why I have such warning and how it is possible to avoid it.

Thanks for helps

**Comment by mstahv** [comment]
This is [a bug in Vaadin](http://dev.vaadin.com/ticket/16348). Nothing serious. It probably actually don't relate to FormLayout, but AbstractForm. The recent version has a workaround to avoid these warnings in some cases. Be sure to use latest version, otherwise, ignore it and vote for the Vaadin issue.

**Comment by mstahv** [comment]
This should finally be closed in 7.6 series, so I'll close this now.
